name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 8.0.2
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: 
    git:
      url: https://github.com/gustamor/flutter_compass.git
      ref: main
  flutter_map: ^6.0.1
  geolocator: ^10.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter:
